/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import java.sql.*;
import ConnectionProvider.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author green
 */
public class updateresults extends javax.swing.JFrame {

    /**
     * Creates new form updateresults
     */
    public updateresults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddStudent = new javax.swing.JButton();
        updateresults = new javax.swing.JButton();
        regstudents = new javax.swing.JButton();
        results = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        Rollno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Physics = new javax.swing.JTextField();
        Maths = new javax.swing.JTextField();
        Chemistry = new javax.swing.JTextField();
        Electrical = new javax.swing.JTextField();
        Economics = new javax.swing.JTextField();
        Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(590, 420));
        setSize(new java.awt.Dimension(590, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddStudent.setBackground(new java.awt.Color(0, 255, 102));
        AddStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddStudent.setText("Add Student");
        AddStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddStudent.setPreferredSize(new java.awt.Dimension(200, 25));
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });
        jPanel1.add(AddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        updateresults.setBackground(new java.awt.Color(0, 255, 102));
        updateresults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateresults.setText("Update Results");
        updateresults.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateresults.setEnabled(false);
        updateresults.setPreferredSize(new java.awt.Dimension(200, 25));
        updateresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateresultsActionPerformed(evt);
            }
        });
        jPanel1.add(updateresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, -1));

        regstudents.setBackground(new java.awt.Color(0, 255, 102));
        regstudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regstudents.setText("Registered Students");
        regstudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regstudents.setPreferredSize(new java.awt.Dimension(200, 25));
        regstudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regstudentsActionPerformed(evt);
            }
        });
        jPanel1.add(regstudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, -1));

        results.setBackground(new java.awt.Color(0, 255, 102));
        results.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        results.setText("List of Students'  Results");
        results.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        results.setPreferredSize(new java.awt.Dimension(200, 25));
        results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsActionPerformed(evt);
            }
        });
        jPanel1.add(results, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, -1));

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setText("LOGOUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setPreferredSize(new java.awt.Dimension(200, 25));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 360, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 420));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(364, 420));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("UPDATE RESULTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 18, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Course", "Branch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 105, 358, 55));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter Roll No.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, 99, -1));

        Search.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel2.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 61, -1, -1));

        Rollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollnoActionPerformed(evt);
            }
        });
        jPanel2.add(Rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 63, 134, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Physics");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 178, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Maths");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 218, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Chemistry");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 258, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Electrical");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 298, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Economics");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 338, -1, -1));
        jPanel2.add(Physics, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 178, 100, -1));
        jPanel2.add(Maths, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 218, 100, -1));
        jPanel2.add(Chemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 258, 100, -1));
        jPanel2.add(Electrical, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 298, 100, -1));
        jPanel2.add(Economics, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 338, 100, -1));

        Update.setBackground(new java.awt.Color(51, 102, 255));
        Update.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 378, 108, 36));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 370, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddStudent().setVisible(true);
    }//GEN-LAST:event_AddStudentActionPerformed

    private void updateresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateresultsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new updateresults().setVisible(true);
    }//GEN-LAST:event_updateresultsActionPerformed

    private void regstudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regstudentsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new regstudents().setVisible(true);
    }//GEN-LAST:event_regstudentsActionPerformed

    private void resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new results().setVisible(true);
    }//GEN-LAST:event_resultsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int flag = JOptionPane.showConfirmDialog(rootPane, "Are You Sure?", "LOGOUT", JOptionPane.YES_NO_OPTION);
        if(flag==0){
            setVisible(false);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void RollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollnoActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String roll = Rollno.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = st.executeQuery("Select name,gender,course,branch from student where rollno='"+roll+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first())
                JOptionPane.showMessageDialog(rootPane, "Entered Roll No. is not in database.");
            else
                Rollno.setEditable(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String roll = Rollno.getText();
        int physics = Integer.parseInt((String)Physics.getText());
        int maths = Integer.parseInt((String)Maths.getText());
        int chemistry = Integer.parseInt((String)Chemistry.getText());
        int electrical = Integer.parseInt((String)Electrical.getText());
        int Eco = Integer.parseInt((String)Economics.getText());
        int total = physics + maths + chemistry + electrical + Eco;
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = st.executeQuery("Select * from results where rollno='"+roll+"'");
            if(!rs.first()){
                String temp = "insert into results values('"+roll+"',"+physics+","+maths+","+chemistry+","+electrical+","+Eco+","+total+")";
                st.executeUpdate(temp);
            }
            else{
                st.executeUpdate("update results set physics="+physics+",maths="+maths+",chemistry="+chemistry+",electrical="+electrical+",economics="+Eco+",total="+total+" where rollno='"+roll+"'");
            }
            setVisible(false);
            new updateresults().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateresults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateresults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateresults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateresults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateresults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudent;
    private javax.swing.JTextField Chemistry;
    private javax.swing.JTextField Economics;
    private javax.swing.JTextField Electrical;
    private javax.swing.JTextField Maths;
    private javax.swing.JTextField Physics;
    private javax.swing.JTextField Rollno;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout;
    private javax.swing.JButton regstudents;
    private javax.swing.JButton results;
    private javax.swing.JButton updateresults;
    // End of variables declaration//GEN-END:variables
}
